module.exports=[{
    id:1,
    username:"arshad@kallarakal",
    name:"arshad",
    email:"arshadkallarakal@gmail.com"
},{
    id:2,
    username:"akhil@mannur",
    name:"akhil",
    email:"akhilmannur@gmail.com"
}]